name: Sync Notion Blogs to GitHub
on:
  schedule:
    # “At minute 0 past every 6th hour.”
    - cron: "0 */6 * * *"
jobs:
  Fetch-Notion-Blogs-and-Write-to-File:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Create .env file
        run: |
          touch .env
          echo NOTION_TOKEN=${{ secrets.NOTION_TOKEN }} >> .env
          echo NOTION_BLOGS_DATABASE_ID=${{ secrets.NOTION_BLOGS_DATABASE_ID }} >> .env
      - name: Fetch Notion Blogs and Wirte to File
        run: |
          yarn
          yarn dev
