name: Sync Notion Blogs to GitHub
on:
  schedule:
    # At 00:00 on every day-of-week
    - cron: '0 0 * * */1'
jobs:
  Fetch-Notion-Blogs-and-Write-to-File:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Create .env file
        run: |
          touch .env
          echo SANITY_PROJECT_ID=${{ secrets.SANITY_PROJECT_ID }} >> .env
      - name: Fetch Notion Blogs and Wirte to File
        run: |
          yarn
          yarn dev
